server:
  applicationConnectors:
  - type: http
    port: 8080

logging:
  level: INFO
  appenders:
    - type: console
      logFormat: "%p [%t] %c{1} - %m%n"

aws:
  key: AKIAI7WQTYQ22BDTOQ6A
  secret: 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
